module RequestTrail
  class Subscriber
    SQL_EVENT: String
    CACHE_READ_EVENT: String
    CACHE_WRITE_EVENT: String

    self.@attach: Array[untyped]?

    def self.attach: () -> Array[untyped]
    def self.detach: () -> nil

    private

    def self.sql_subscription: () -> untyped
    def self.cache_read_subscription: () -> untyped
    def self.cache_write_subscription: () -> untyped
  end
end